# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.6
maven_group = net.oxcodsnet.beltborne_lanterns
archives_name = beltborne_lanterns

# ===============================================
# Minecraft properties

minecraft_version = 26.1
neoform_version = 1.21.10-20251010.172816

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.155.2+26.1.2

neoforge_version = 21.10.47-beta

cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8

# ===============================================
mod_id=beltborne_lanterns
mod_name=Beltborne Lanterns
mod_description=Beltborne Lanterns - free hands, bright path!\n\nPress *B* while holding a lantern - it snaps onto your belt. Walk, jump, fight - the lantern sways with physics and casts light near you. Need it back in your hands - Press *B* again.\n\nPorted to MC 26.1-26.2 by nuramri23.
mod_authors=0xCoDSnet, nuramri23
mod_homepage=https://modrinth.com/mod/beltborne-lanterns-unofficial-mc-26.1-port
mod_sources=https://modrinth.com/mod/beltborne-lanterns-unofficial-mc-26.1-port
mod_license=Apache-2.0


# Optional integrations
# LambDynamicLights 4.x (for compileOnly usage)
lambdynamiclights_version=4.10.0+26.1
